### ISSUE TITLE
Netty 4.1 support

### ISSUE THREAD

**Issue by flowersinthesand** [cettia/asity#22]
According to http://netty.io/wiki/new-and-noteworthy-in-4.1.html, Netty 4.1 is not fully backward-compatible with 4.0. After upgrading Netty from 4.0 to 4.1, I found that unit tests of Netty bridge fail.

Since its major version is still 4, I don't want to create a new module for only 4.1. Let's try to resolve it within only one module by leveraging reflection.

**Comment by flowersinthesand** [comment]
Here are errors after upgrading 4.0 to 4.1:

```
Information:java: Errors occurred while compiling module 'asity-bridge-netty4'
Information:javac 1.8.0_112 was used to compile java sources
Information:Module "asity-bridge-netty4" was fully rebuilt due to project configuration/dependencies changes
Information:05/06/2018, 2:33 PM - Compilation completed with 5 errors and 14 warnings in 13s 503ms
/Users/donghwankim/git/asity/bridge-netty4/src/main/java/io/cettia/asity/bridge/netty4/AsityServerCodec.java
    Error:Error:line (39)java: package io.netty.handler.ssl does not exist
    Error:Error:line (40)java: package io.netty.handler.timeout does not exist
    Warning:Warning:line (83)java: getMethod() in io.netty.handler.codec.http.HttpRequest has been deprecated
    Warning:Warning:line (83)java: io.netty.handler.codec.http.HttpHeaders.Names in io.netty.handler.codec.http.HttpHeaders has been deprecated
    Warning:Warning:line (84)java: io.netty.handler.codec.http.HttpHeaders.Values in io.netty.handler.codec.http.HttpHeaders has been deprecated
    Warning:Warning:line (86)java: getProtocolVersion() in io.netty.handler.codec.http.HttpMessage has been deprecated
    Warning:Warning:line (87)java: getMethod() in io.netty.handler.codec.http.HttpRequest has been deprecated
    Warning:Warning:line (87)java: getUri() in io.netty.handler.codec.http.HttpRequest has been deprecated
    Error:Error:line (91)java: cannot find symbol
  symbol:   class ReadTimeoutHandler
  location: class io.cettia.asity.bridge.netty4.AsityServerCodec
    Error:Error:line (104)java: cannot find symbol
  symbol:   class ReadTimeoutHandler
  location: class io.cettia.asity.bridge.netty4.AsityServerCodec
    Error:Error:line (140)java: cannot find symbol
  symbol:   class SslHandler
  location: class io.cettia.asity.bridge.netty4.AsityServerCodec
    Warning:Warning:line (140)java: getHost(io.netty.handler.codec.http.HttpMessage) in io.netty.handler.codec.http.HttpHeaders has been deprecated
    Warning:Warning:line (141)java: getUri() in io.netty.handler.codec.http.HttpRequest has been deprecated
/Users/donghwankim/git/asity/bridge-netty4/src/main/java/io/cettia/asity/bridge/netty4/NettyServerWebSocket.java
    Warning:Warning:line (72)java: getUri() in io.netty.handler.codec.http.HttpRequest has been deprecated
/Users/donghwankim/git/asity/bridge-netty4/src/main/java/io/cettia/asity/bridge/netty4/NettyServerHttpExchange.java
    Warning:Warning:line (54)java: getProtocolVersion() in io.netty.handler.codec.http.HttpMessage has been deprecated
    Warning:Warning:line (56)java: io.netty.handler.codec.http.HttpHeaders.Names in io.netty.handler.codec.http.HttpHeaders has been deprecated
    Warning:Warning:line (56)java: io.netty.handler.codec.http.HttpHeaders.Values in io.netty.handler.codec.http.HttpHeaders has been deprecated
    Warning:Warning:line (69)java: getUri() in io.netty.handler.codec.http.HttpRequest has been deprecated
    Warning:Warning:line (74)java: getMethod() in io.netty.handler.codec.http.HttpRequest has been deprecated
```

**Comment by flowersinthesand** [comment]
It's simply resolved by adding `io.netty:netty-handler:4.1.25.Final` to bridge's pom.xml.
